server:
  servlet:
    context-path: /meal_plan
  port: 8084
spring:
  application:
    name: Recipes app
  datasource:
    url: jdbc:postgresql://localhost:5433/recipe_test
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
ingredients:
  service:
    url: http://localhost:8083/meal_plan