CREATE DATABASE recipe;
CREATE DATABASE recipe_test;

CREATE USER postgres WITH PASSWORD 'password';

GRANT ALL PRIVILEGES ON DATABASE recipe_test TO postgres;
GRANT ALL PRIVILEGES ON DATABASE postgres TO postgres;

